<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();
        $threeDaysAgo = Carbon::now()->subDays(3);
        $aWeekAgo = Carbon::now()->subWeek();
        $twoWeeksAgo = Carbon::now()->subWeek();
        $aMonthAgo = Carbon::now()->subMonth();

        $products = [
            [
                'product_id' => 'P002',
                'status_master_id' => '1',
                'category_master_id' => '',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => '1.jpg',
                'name' => 'shoe ',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P003',
                'status_master_id' => '1',
                'category_master_id' => '',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => '2.jpg',
                'name' => 'Blue jacket',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P004',
                'status_master_id' => '1',
                'category_master_id' => '',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => '3.jpg',
                'name' => 'Clothes one',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P005',
                'status_master_id' => '1',
                'category_master_id' => '',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => '4.jpg',
                'name' => 'brown cap',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $twoWeeksAgo,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'belt.jpg',
                'name' => "Men's Leather Reversible Belt",
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'clothes-1.jpg',
                'name' => 'Relaxed Short full Sleeve T-Shirt',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'clothes-2.jpg',
                'name' => 'Girls pnk Embro design Top',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'clothes-3.jpg',
                'name' => 'Black Floral Wrap Midi Skirt',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'clothes-4.jpg',
                'name' => 'clothes-4',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'jacket-1.jpg',
                'name' => 'Mens Winter Leathers Jackets',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'jacket-2.jpg',
                'name' => 'jacket-2',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'jacket-3.jpg',
                'name' => 'Mens Winter Leathers Jackets',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'jacket-4.jpg',
                'name' => 'jacket-4',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'jacket-5.jpg',
                'name' => 'MEN Yarn Fleece Full-Zip Jacket',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'jacket-6.jpg',
                'name' => 'jacket-6',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '10',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'jewellery-1.jpg',
                'name' => 'Rose Gold Peacock Earrings',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '10',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'jewellery-2.jpg',
                'name' => 'platinum Zircon Classic Ring',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '10',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'jewellery-3.jpg',
                'name' => 'Silver Deer Heart Necklace',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '5',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'party-wear-1.jpg',
                'name' => 'Womens Party Wear Shoes',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '5',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'party-wear-2.jpg',
                'name' => 'party-wear-2',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '13',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'perfume.jpg',
                'name' => 'Titan 100 Ml Womens Perfume',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '18',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'shampoo.jpg',
                'name' => 'shampoo conditioner packs',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '1',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'shirt-1.jpg',
                'name' => 'Pure Garment Dyed Cotton Shirt',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '1',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'shirt-2.jpg',
                'name' => 'shirt-2',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '5',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'shoe-1.jpg',
                'name' => "Men's Leather Formal Wear shoes",
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '5',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'shoe-2.jpg',
                'name' => "Casual Men's Brown shoes",
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '5',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'shoe-3.jpg',
                'name' => 'Boot With Suede Detail',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '5',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'shoe-4.jpg',
                'name' => 'shoe-4',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '5',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'shoe-5.jpg',
                'name' => 'shoe-5',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '1',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'shorts-1.jpg',
                'name' => 'Better Basics French Terry Sweatshorts',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '1',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'shorts-2.jpg',
                'name' => 'shorts-2',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '5',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'sports-1.jpg',
                'name' => 'Running & Trekking Shoes - White',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '5',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'sports-2.jpg',
                'name' => 'Trekking & Running Shoes - black',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '5',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'sports-3.jpg',
                'name' => "Sports Claw Women's Shoes",
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '5',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'sports-4.jpg',
                'name' => 'sports-4',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '5',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'sports-5.jpg',
                'name' => 'sports-5',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '5',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'sports-6.jpg',
                'name' => 'Air Trekking Shoes - white',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '5',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'watch-1.jpg',
                'name' => 'Smart watche Vital Plus',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '5',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'watch-2.jpg',
                'name' => 'watch-2',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '5',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'watch-2.jpg',
                'name' => 'watch-2',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $now,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '5',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'watch-3.jpg',
                'name' => 'Pocket Watch Leather Pouch',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $threeDaysAgo,

            ],
            [
                'product_id' => 'P00'.rand(0, 100),
                'status_master_id' => '1',
                'category_master_id' => '5',
                'cat_sub_from' => '',
                'price_master_id' => 100,
                'image_banner' => 'watch-4.jpg',
                'name' => 'watch-4',
                'barcode' => '123456'.rand(0, 100),
                'is_sold' => 1,
                'size' => 'M',
                'rating' => 4,
                'wishlist' => 'Sample Wishlist',
                'lang' => 'en',
                'lang_id' => '1',
                'created_by' => 'admin',
                'updated_by' => 'admin',
                'created_at' => $threeDaysAgo,

            ],
        ];

        // Insert data into the products table
        DB::table('products')->insert($products);
    }

    
}
